-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 17:24:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_auditoria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_auditoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_auditoria` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_auditoria` ;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre_pri_per` VARCHAR(45) NOT NULL,
  `nombre_seg_per` VARCHAR(45) NULL,
  `apellido_pri_per` VARCHAR(45) NOT NULL,
  `apellido_seg_per` VARCHAR(45) NULL,
  `tipo_doc_per` VARCHAR(45) NOT NULL,
  `num_documento` VARCHAR(45) NOT NULL,
  `num_celular` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `fecha_nac_per` DATE NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `cod_contrato_usu` VARCHAR(45) NOT NULL,
  `pass_usu` VARCHAR(150) NOT NULL,
  `estado_usu` TINYINT NOT NULL,
  `perfil_usu` VARCHAR(100) NULL,
  `pregunta_seg_usu` VARCHAR(255) NULL,
  `respuesta_seg_usu` VARCHAR(25) NULL,
  `temporalida_usu` DATE NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `proyecto_auditoria`.`persona` (`id_persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`areas` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_encargado` INT NOT NULL,
  `nombre_unidad` VARCHAR(45) NOT NULL,
  `certificado` TINYINT NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_area`),
  CONSTRAINT `fk_unidadNegocio_usuario`
    FOREIGN KEY (`id_usuario_encargado`)
    REFERENCES `proyecto_auditoria`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL,
  `estado_rol` TINYINT NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`usuario_rol` (
  `id_usuario_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_usuario_rol`),
  CONSTRAINT `fk_usuarioRol_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `proyecto_auditoria`.`rol` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarioRol_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `proyecto_auditoria`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`vacaciones` (
  `id_vacaciones` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado_vacaciones` TINYINT NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_vacaciones`),
  CONSTRAINT `fk_vaciones_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `proyecto_auditoria`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`auditoria_programacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`auditoria_programacion` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `id_area` INT NOT NULL,
  `id_usu_auditor` INT NOT NULL,
  `tipo_auditoria` VARCHAR(45) NOT NULL,
  `fecha_programacion` DATE NOT NULL,
  `estado_auditoria` ENUM('Inicializada', 'En proceso', 'Finalizada') NOT NULL COMMENT 'Agregar los estados de una auditoria',
  `observacion` MEDIUMTEXT NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_auditoria`),
  CONSTRAINT `fk_auditoria_area`
    FOREIGN KEY (`id_area`)
    REFERENCES `proyecto_auditoria`.`areas` (`id_area`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auditoria_usuario`
    FOREIGN KEY (`id_usu_auditor`)
    REFERENCES `proyecto_auditoria`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`ejecucion_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`ejecucion_auditoria` (
  `id_ejecucion_auditoria` INT NOT NULL AUTO_INCREMENT,
  `id_auditoria_programada` INT NOT NULL COMMENT 'Auditor lider encargado de la auditoria',
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_ejecucion_auditoria`),
  CONSTRAINT `fk_audP_audE`
    FOREIGN KEY (`id_auditoria_programada`)
    REFERENCES `proyecto_auditoria`.`auditoria_programacion` (`id_auditoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`anexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`anexos` (
  `id_anexo` INT NOT NULL AUTO_INCREMENT,
  `id_ejecucion_auditoria` INT NOT NULL,
  `nombre_anexo` VARCHAR(255) NOT NULL,
  `estado_anexo` ENUM('Sin validar', 'Primera validacióm', 'Segunda validación') NOT NULL,
  `ruta_anexo` VARCHAR(255) NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_anexo`),
  CONSTRAINT `fk_anexo_ejecuAud`
    FOREIGN KEY (`id_ejecucion_auditoria`)
    REFERENCES `proyecto_auditoria`.`ejecucion_auditoria` (`id_ejecucion_auditoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`trasa_anexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`trasa_anexos` (
  `id_trasa_anexos` INT NOT NULL AUTO_INCREMENT,
  `id_anexo` INT NOT NULL,
  `id_usuario_validacion` INT NOT NULL,
  `fecha_validacion` DATE NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_trasa_anexos`),
  CONSTRAINT `fk_tras_anexo`
    FOREIGN KEY (`id_anexo`)
    REFERENCES `proyecto_auditoria`.`anexos` (`id_anexo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`hallazgo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`hallazgo` (
  `id_hallazgo` INT NOT NULL AUTO_INCREMENT,
  `id_ejecucion_auditoria` INT NOT NULL,
  `fecha_hallazgo` DATETIME NOT NULL,
  `acciones_planeada` MEDIUMTEXT NOT NULL,
  `ruta_evidencia` VARCHAR(255) NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_hallazgo`),
  CONSTRAINT `fk_hallazgo_auditoria`
    FOREIGN KEY (`id_ejecucion_auditoria`)
    REFERENCES `proyecto_auditoria`.`ejecucion_auditoria` (`id_ejecucion_auditoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`plan_mejoramiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`plan_mejoramiento` (
  `id_plan_mejoramiento` INT NOT NULL AUTO_INCREMENT,
  `id_hallazgo` INT NOT NULL,
  `aspecto_mejora` MEDIUMTEXT NOT NULL,
  `acciones_planteadas` TEXT NOT NULL,
  `fecha_evidencia` DATE NOT NULL,
  `ruta_evidencia` VARCHAR(255) NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  `estado_plaMejor` ENUM('Abierto', 'Sin avance', 'Cerrado', 'Vencido') NOT NULL,
  PRIMARY KEY (`id_plan_mejoramiento`),
  CONSTRAINT `fk_plan_hallazgo`
    FOREIGN KEY (`id_hallazgo`)
    REFERENCES `proyecto_auditoria`.`hallazgo` (`id_hallazgo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_auditoria`.`prorroga_mejoramiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_auditoria`.`prorroga_mejoramiento` (
  `id_prorroga_mejoramiento` INT NOT NULL,
  `id_plan_mejoramiento` INT NOT NULL,
  `fecha_adicional` VARCHAR(45) NOT NULL,
  `id_usuario_creacion` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_prorroga_mejoramiento`),
  CONSTRAINT `fk_prorroga_planMejora`
    FOREIGN KEY (`id_plan_mejoramiento`)
    REFERENCES `proyecto_auditoria`.`plan_mejoramiento` (`id_plan_mejoramiento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
